/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

// yo big thanks to Java for autogenerated methods

package menuframework;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 *
 * @author Ali
 */
public class MenuOptionMap<OptionType extends MenuOptionType> implements Map<OptionType, MenuOptionBranch<OptionType>> {
    private Set<Entry<OptionType, MenuOptionBranch<OptionType>>> entries; 
    
    public MenuOptionMap() {
        entries = new LinkedHashSet<>(); // Insertion order 100% matters!
    }
    
    // This whole class just for this
    public MenuOptionBranch<OptionType> getRaw(String raw) {
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            if (entry.getKey().is(raw)) {
                return entry.getValue();
            }
        }
        return null;
    }
    
    /* Map Methods */

    @Override
    public int size() {
        return entries.size();
    }

    @Override
    public boolean isEmpty() {
        return entries.isEmpty();
    }

    @Override
    public boolean containsKey(Object key) {
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            if (Objects.equals(entry.getKey(), key)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public boolean containsValue(Object value) {
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            if (Objects.equals(entry.getValue(), value)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public MenuOptionBranch<OptionType> get(Object key) {
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            if (Objects.equals(entry.getKey(), key)) {
                return entry.getValue();
            }
        }
        return null;
    }

    @Override
    public MenuOptionBranch<OptionType> put(OptionType key, MenuOptionBranch<OptionType> value) {
        if (key == null || value == null) {
            throw new NullPointerException("Key or value cannot be null");
        }
        
        // Check if the key already exists
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            if (Objects.equals(entry.getKey(), key)) {
                // If key exists, update the value
                MenuOptionBranch<OptionType> oldValue = entry.getValue();
                entry.setValue(value);
                return oldValue;
            }
        }
        // If key doesn't exist, add a new entry
        entries.add(new AbstractMap.SimpleEntry<>(key, value));
        return null;
    }

    @Override
    public MenuOptionBranch<OptionType> remove(Object key) {
        Iterator<Entry<OptionType, MenuOptionBranch<OptionType>>> iterator = entries.iterator();
        while (iterator.hasNext()) {
            Entry<OptionType, MenuOptionBranch<OptionType>> entry = iterator.next();
            if (Objects.equals(entry.getKey(), key)) {
                iterator.remove();
                return entry.getValue();
            }
        }
        return null;
    }

    @Override
    public void putAll(Map<? extends OptionType, ? extends MenuOptionBranch<OptionType>> m) {
        for (Entry<? extends OptionType, ? extends MenuOptionBranch<OptionType>> entry : m.entrySet()) {
            put(entry.getKey(), entry.getValue());
        }
    }

    @Override
    public void clear() {
        entries.clear();
    }

    @Override
    public Set<OptionType> keySet() {
        Set<OptionType> keySet = new LinkedHashSet<>();
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            keySet.add(entry.getKey());
        }
        return keySet;
    }

    @Override
    public Collection<MenuOptionBranch<OptionType>> values() {
        List<MenuOptionBranch<OptionType>> values = new ArrayList<>();
        for (Entry<OptionType, MenuOptionBranch<OptionType>> entry : entries) {
            values.add(entry.getValue());
        }
        return values;
    }

    @Override
    public Set<Entry<OptionType, MenuOptionBranch<OptionType>>> entrySet() {
        return entries;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 67 * hash + Objects.hashCode(this.entries);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MenuOptionMap other = (MenuOptionMap) obj;
        return Objects.equals(this.entries, other.entries);
    }

    @Override
    public String toString() {
        return "MenuOptionMap{" + "entries=" + entries + '}';
    }
}
